server:
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    url: jdbc:mysql://39.105.104.195:3306/springboot_all?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: kang
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size= 1:
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
  # redis 配置
  redis:
    database: 1
    host: 39.105.104.195
    port: 6379
    password: kang123456
    jedis:
      pool:
        max-wait: 30000ms
        max-active: 8
        max-idle: 8
        min-idle: 1
    timeout: 6000ms
    # email配置
  mail:
    host: stmp
    username: 1067905926@qq.com
    password:
    default-encoding: UTF-8

#mybatis-plus
mybatis-plus:
  mapper-locations: /mapper/*/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT配置
jwt:
  # 密匙KEY
  secret: JWTSecret
  # HeaderKEY
  tokenHeader: Authorization
  # Token前缀字符
  tokenPrefix: Kang-
  # 过期时间 单位秒 1天后过期=86400 7天后过期=604800
  expiration: 86400
  # 配置不需要认证的接口
  antMatchers: /index/info,/login/**,/favicon.ico,/v2/api-docs, /definitions/**, /configuration/ui, /swagger-resources/**, /configuration/security, /swagger-ui.html, /webjars/**,/swagger-resources/configuration/ui,/swagge‌​r-ui.html

logging:
  config: classpath:config/logback/logback-spring.xml
  file:
    path: E:/log/quickLog
